version: '2'

services:
  busybox:
    image: busybox
    volumes:
      - .:/data

  web:
    build: .
    ports:
      - "80:80"
      - "82:82"
    volumes:
      - .:/data

  database:
    image: centos/postgresql-95-centos7
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USER=user
      - POSTGRESQL_PASSWORD=pass
      - POSTGRESQL_DATABASE=db